# Base image
FROM python:3.10-alpine

# Install rust
# RUN apt-get update
# RUN apt-get install -y curl gcc
# # RUN apk add curl gcc
# RUN curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh -s -- -y
# ENV PATH="/root/.cargo/bin:${PATH}"
# RUN rustc --version

# Installing build requirements
RUN apk add gcc g++ cmake make
# RUN apk add python3-dev musl-dev linux-headers make cmake
# RUN apt-get install -y python3-dev
# RUN rustc --version
# RUN apk add python3-dev gcc

# Working directory within the container
WORKDIR /app 

# Install dependencies
COPY requirements.txt ./
# RUN pip install -r requirements.txt
RUN pip install flask skforecast xgboost

# Copy your essential files
COPY models/forecaster_hawaii_m.pkl ./
COPY main.py ./

# Execute your inference script 
CMD ["flask", "--app", "main.py", "run", "--host=0.0.0.0"]
