name: Azure Container Apps Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'

      - name: Determine Semantic Version using GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and deploy Container App [v${{ steps.gitversion.outputs.SemVer }}]
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          acrName: farmserviceacr1
          containerAppName: farmservice-predictor
          resourceGroup: farmservice_rg
          dockerfilePath: Dockerfile-slim
          imageToBuild: farmserviceacr1.azurecr.io/farmservice-predictor:${{ steps.gitversion.outputs.SemVer }}
          containerAppEnvironment: managedEnvironment-farmservicerg-a942
          

